name: govulncheck
on:
  push:
    paths:
      - go.sum
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions: read-all

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-slim
    # Currently ubuntu-slim does not supply a ImageOS variable, used to match go cache
    env:
      ImageOS: "x64-ubuntu24"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Go Generate
        run: |
          ./scripts/download
          go generate
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -format=text ./...
